[package]
name = "keechain-common"
version = "0.1.0"
edition = "2021"
description = "KeeChain Common library."
authors = ["Yuki Kishimoto <yukikishimoto@protonmain.com>"]
readme = "README.md"

[dependencies]
dirs = "4.0"
